# Generated by Django 4.2.16 on 2024-09-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="interface_crud_employe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=100)),
                ("photo", models.CharField(max_length=100)),
            ],
        ),
    ]
