# Generated by Django 4.2.16 on 2024-09-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface_crud_employe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interface_crud_employe",
            old_name="numero",
            new_name="contact",
        ),
    ]
